### ISSUE TITLE
Modularize functions

### ISSUE THREAD

**Issue by Parthav46** [Parthav46/PaytmIntegrationSampleServer#3]
Currently all the functions are written in index.js
Divide it into different files and import them to index.js

**Comment by 13samyakjain** [comment]
Can I do this?

**Comment by Parthav46** [comment]
@13samyakjain please give an estimated time for solving this issue or i will assign it to someone else

**Comment by 13samyakjain** [comment]
Sorry I cannot continue this

**Comment by rhythm1920** [comment]
Can I take up this issue??

**Comment by rhythm1920** [comment]
@Parthav46 Do you want all three functions `test` , `response` and `checksum` to be modularized??
Since there is a already a `checksum.js` in the `functions` folder. What name should I give to it or should I place the functions in a separate folder??

**Comment by Parthav46** [comment]
place the functions in a separate folder
