### ISSUE TITLE
Setup CI for project

### ISSUE THREAD

**Issue by Parthav46** [Parthav46/PaytmIntegrationSampleServer#6]
Add CI using CircleCI for the project to pass tests

**Comment by Parthav46** [comment]
make PR to [circleci-project-setup](https://github.com/Parthav46/PaytmIntegrationSampleServer/tree/circleci-project-setup)

**Comment by AugustasV** [comment]
I would like to do that!

**Comment by AugustasV** [comment]
out of package.json file couldn't understand how you would like to run tests. Also, does it have any? What command do you use to run those? Can you wrote those commands

**Comment by Parthav46** [comment]
That is still remaining. I will create tests after I migrate the code for heroku. I will ping you here once that is done.

**Comment by AugustasV** [comment]
Maybe you can create some dummy test that we could run and in that way, I could do a pipeline?

**Comment by Parthav46** [comment]
@AugustasV I have added dummy tests

**Comment by Parthav46** [comment]
@AugustasV Apparently the current circleci config already runs test so probably there is no need for this issue. Still if you feel something can be added in there do tell me about it.
